local r=dofile('lib/RenderRecovery.lua').new()
assert(r:ready('pallet'));r:failed('atlas');assert(not r:ready('pallet'))
r:update(.5);assert(not r:ready('pallet'));r:update(.5);assert(r:ready('pallet'))
r:failed('atlas');r:update(2);assert(r:ready('pallet'));r:failed('atlas');r:update(100)
assert(not r:ready('pallet'),'permanent fault retried every frame')
assert(r:ready('route1'),'one map poisoned the entire session');r:succeeded()
assert(r:ready('pallet'),'return to old map was permanently disabled')
r:failed('atlas');r:reset();assert(r:ready('pallet'),'manual camera reset did not retry')
print('PASS bounded transient retries, area recovery, revisit and manual reset')
