-- The importer adds generated pairs to Versions only while importing a ROM.
-- Cached boots retain their names on the map, but not those table entries.
-- Decode the importer's public pair naming convention; never read ROM/cache
-- files or interpret the opaque secondary suffix as an address.
local V=...
local M={}
local profiles=V and V.require('Gen3InteriorProfiles') or dofile((os.getenv('DS_MOD_PATH') or '.')..'/lib/Gen3InteriorProfiles.lua')
-- Resolve edition-specific generated pair names through public map identity.
-- No ROM addresses or imported files are read at runtime. Full drawing recipes
-- still validate each object before claiming it.
local aliases={}
local representatives={
 ['building__rom_082d4bcc']={'FR_CERULEAN_CITY_MART','FR_CINNABAR_ISLAND_MART','FR_FOUR_ISLAND_MART','FR_FUCHSIA_CITY_MART','FR_LAVENDER_TOWN_MART','FR_PEWTER_CITY_MART','FR_SAFFRON_CITY_MART','FR_SEVEN_ISLAND_MART','FR_SIX_ISLAND_MART','FR_THREE_ISLAND_MART','FR_VERMILION_CITY_MART','FR_VIRIDIAN_CITY_MART'},
 ['building__rom_082d4c2c']={'FR_FIVE_ISLAND_RESORT_GORGEOUS_HOUSE','FR_FUCHSIA_CITY_HOUSE2','FR_FUCHSIA_CITY_WARDENS_HOUSE','FR_PEWTER_CITY_MUSEUM_1F','FR_PEWTER_CITY_MUSEUM_2F'},
 ['building__rom_082d4c44']={'FR_BATTLE_COLOSSEUM_2P','FR_BATTLE_COLOSSEUM_4P','FR_RECORD_CORNER','FR_TRADE_CENTER'},
 ['building__rom_082d4c5c']={'FR_CERULEAN_CITY_BIKE_SHOP'},
 ['building__rom_082d4ca4']={'FR_FUCHSIA_CITY_GYM'},
 ['building__rom_082d4cbc']={'FR_VIRIDIAN_CITY_GYM'},
 ['building__rom_082d4cec']={'FR_CELADON_CITY_GAME_CORNER','FR_CELADON_CITY_GAME_CORNER_PRIZE_ROOM','FR_TWO_ISLAND_JOYFUL_GAME_CORNER'},
 ['building__rom_082d4d1c']={'FR_CERULEAN_CITY_GYM'},
 ['building__rom_082d4d34']={'FR_VERMILION_CITY_GYM'},
 ['building__rom_082d4d4c']={'FR_CELADON_CITY_GYM'},
 ['building__rom_082d4d64']={'FR_SAFFRON_CITY_GYM'},
 ['building__rom_082d4d7c']={'FR_CINNABAR_ISLAND_GYM'},
 ['building__rom_082d4e24']={'FR_SEVEN_ISLAND_HOUSE_ROOM1'},
 ['building__rom_082d4e6c']={'FR_CELADON_CITY_DEPARTMENT_STORE_1F','FR_CELADON_CITY_DEPARTMENT_STORE_2F','FR_CELADON_CITY_DEPARTMENT_STORE_3F','FR_CELADON_CITY_DEPARTMENT_STORE_4F','FR_CELADON_CITY_DEPARTMENT_STORE_5F','FR_CELADON_CITY_DEPARTMENT_STORE_ROOF'},
 ['building__rom_082d4e9c']={'FR_POWER_PLANT'},
 ['building__rom_082d4eb4']={'FR_ROUTE_25_SEA_COTTAGE'},
 ['building__rom_082d4ecc']={'FR_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR','FR_FIVE_ISLAND_ROCKET_WAREHOUSE','FR_ROCKET_HIDEOUT_B1F','FR_ROCKET_HIDEOUT_B2F','FR_ROCKET_HIDEOUT_B3F','FR_ROCKET_HIDEOUT_B4F','FR_ROCKET_HIDEOUT_ELEVATOR','FR_SILPH_CO_10F','FR_SILPH_CO_11F','FR_SILPH_CO_1F','FR_SILPH_CO_2F','FR_SILPH_CO_3F','FR_SILPH_CO_4F','FR_SILPH_CO_5F','FR_SILPH_CO_6F','FR_SILPH_CO_7F','FR_SILPH_CO_8F','FR_SILPH_CO_9F','FR_SILPH_CO_ELEVATOR','FR_TRAINER_TOWER_ELEVATOR'},
 ['building__rom_082d4ee4']={'FR_UNDERGROUND_PATH_EAST_WEST_TUNNEL','FR_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL'},
 ['building__rom_082d4efc']={'FR_POKEMON_TOWER_1F','FR_POKEMON_TOWER_2F','FR_POKEMON_TOWER_3F','FR_POKEMON_TOWER_4F','FR_POKEMON_TOWER_5F','FR_POKEMON_TOWER_6F','FR_POKEMON_TOWER_7F'},
 ['building__rom_082d4f14']={'FR_FOUR_ISLAND_LORELEIS_HOUSE','FR_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE','FR_FUCHSIA_CITY_SAFARI_ZONE_OFFICE','FR_SAFARI_ZONE_CENTER_REST_HOUSE','FR_SAFARI_ZONE_EAST_REST_HOUSE','FR_SAFARI_ZONE_NORTH_REST_HOUSE','FR_SAFARI_ZONE_SECRET_HOUSE','FR_SAFARI_ZONE_WEST_REST_HOUSE'},
 ['building__rom_082d4f2c']={'FR_POKEMON_MANSION_1F','FR_POKEMON_MANSION_2F','FR_POKEMON_MANSION_3F','FR_POKEMON_MANSION_B1F'},
 ['building__rom_082d4f44']={'FR_CELADON_CITY_HOTEL','FR_CELADON_CITY_RESTAURANT'},
 ['building__rom_082d4f5c']={'FR_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM','FR_VIRIDIAN_CITY_SCHOOL'},
 ['building__rom_082d4f74']={'FR_FOUR_ISLAND_POKEMON_DAY_CARE','FR_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE','FR_ROUTE_5_POKEMON_DAY_CARE','FR_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB','FR_VERMILION_CITY_POKEMON_FAN_CLUB'},
 ['building__rom_082d4f8c']={'FR_CELADON_CITY_CONDOMINIUMS_1F','FR_CELADON_CITY_CONDOMINIUMS_2F','FR_CELADON_CITY_CONDOMINIUMS_3F','FR_CELADON_CITY_CONDOMINIUMS_ROOF'},
 ['building__rom_082d4fa4']={'FR_CERULEAN_CITY_HOUSE2'},
 ['building__rom_082d5034']={'FR_SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER','FR_SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER','FR_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER','FR_SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER','FR_SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER','FR_SEVEN_ISLAND_TANOBY_RUINS_VIAPOIS_CHAMBER','FR_SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER'},
 ['building__rom_082d5094']={'FR_TRAINER_TOWER_1F','FR_TRAINER_TOWER_2F','FR_TRAINER_TOWER_3F','FR_TRAINER_TOWER_4F','FR_TRAINER_TOWER_5F','FR_TRAINER_TOWER_6F','FR_TRAINER_TOWER_7F','FR_TRAINER_TOWER_8F','FR_TRAINER_TOWER_LOBBY','FR_TRAINER_TOWER_ROOF'},
 ['building__rom_082d50c4']={'FR_POKEMON_LEAGUE_AGATHAS_ROOM','FR_POKEMON_LEAGUE_BRUNOS_ROOM','FR_POKEMON_LEAGUE_CHAMPIONS_ROOM','FR_POKEMON_LEAGUE_LANCES_ROOM','FR_POKEMON_LEAGUE_LORELEIS_ROOM'},
 ['building__rom_082d50dc']={'FR_POKEMON_LEAGUE_HALL_OF_FAME','FR_UNION_ROOM'},
 ['general__rom_082d4af4']={'FR_CERULEAN_CITY','FR_ROUTE_24','FR_ROUTE_25','FR_ROUTE_4','FR_ROUTE_5','FR_ROUTE_9'},
 ['general__rom_082d4b0c']={'FR_LAVENDER_TOWN','FR_ROUTE_10','FR_ROUTE_12','FR_ROUTE_13','FR_ROUTE_14','FR_ROUTE_8'},
 ['general__rom_082d4b24']={'FR_ROUTE_11','FR_ROUTE_6','FR_SSANNE_EXTERIOR','FR_VERMILION_CITY'},
 ['general__rom_082d4b3c']={'FR_CELADON_CITY','FR_PROTOTYPE_SEVII_ISLE_6','FR_PROTOTYPE_SEVII_ISLE_7','FR_PROTOTYPE_SEVII_ISLE_8','FR_PROTOTYPE_SEVII_ISLE_9','FR_ROUTE_16','FR_ROUTE_17','FR_ROUTE_18','FR_ROUTE_7'},
 ['general__rom_082d4b54']={'FR_FUCHSIA_CITY','FR_ROUTE_15','FR_ROUTE_19','FR_SAFARI_ZONE_CENTER','FR_SAFARI_ZONE_EAST','FR_SAFARI_ZONE_NORTH','FR_SAFARI_ZONE_WEST'},
 ['general__rom_082d4b6c']={'FR_CINNABAR_ISLAND','FR_ROUTE_20','FR_ROUTE_21_SOUTH'},
 ['general__rom_082d4b84']={'FR_INDIGO_PLATEAU_EXTERIOR','FR_ROUTE_23'},
 ['general__rom_082d4b9c']={'FR_SAFFRON_CITY','FR_SAFFRON_CITY_CONNECTION'},
 ['general__rom_082d4bfc']={'FR_FIVE_ISLAND_LOST_CAVE_ENTRANCE','FR_FIVE_ISLAND_LOST_CAVE_ROOM1','FR_FIVE_ISLAND_LOST_CAVE_ROOM10','FR_FIVE_ISLAND_LOST_CAVE_ROOM11','FR_FIVE_ISLAND_LOST_CAVE_ROOM12','FR_FIVE_ISLAND_LOST_CAVE_ROOM13','FR_FIVE_ISLAND_LOST_CAVE_ROOM14','FR_FIVE_ISLAND_LOST_CAVE_ROOM2','FR_FIVE_ISLAND_LOST_CAVE_ROOM3','FR_FIVE_ISLAND_LOST_CAVE_ROOM4','FR_FIVE_ISLAND_LOST_CAVE_ROOM5','FR_FIVE_ISLAND_LOST_CAVE_ROOM6','FR_FIVE_ISLAND_LOST_CAVE_ROOM7','FR_FIVE_ISLAND_LOST_CAVE_ROOM8','FR_FIVE_ISLAND_LOST_CAVE_ROOM9','FR_MT_MOON_1F','FR_MT_MOON_B1F','FR_MT_MOON_B2F','FR_THREE_ISLAND_DUNSPARCE_TUNNEL','FR_VICTORY_ROAD_1F','FR_VICTORY_ROAD_2F','FR_VICTORY_ROAD_3F'},
 ['general__rom_082d4d94']={'FR_SSANNE_1F_CORRIDOR','FR_SSANNE_1F_ROOM1','FR_SSANNE_1F_ROOM2','FR_SSANNE_1F_ROOM3','FR_SSANNE_1F_ROOM4','FR_SSANNE_1F_ROOM5','FR_SSANNE_1F_ROOM6','FR_SSANNE_1F_ROOM7','FR_SSANNE_2F_CORRIDOR','FR_SSANNE_2F_ROOM1','FR_SSANNE_2F_ROOM2','FR_SSANNE_2F_ROOM3','FR_SSANNE_2F_ROOM4','FR_SSANNE_2F_ROOM5','FR_SSANNE_2F_ROOM6','FR_SSANNE_3F_CORRIDOR','FR_SSANNE_B1F_CORRIDOR','FR_SSANNE_B1F_ROOM1','FR_SSANNE_B1F_ROOM2','FR_SSANNE_B1F_ROOM3','FR_SSANNE_B1F_ROOM4','FR_SSANNE_B1F_ROOM5','FR_SSANNE_CAPTAINS_OFFICE','FR_SSANNE_DECK','FR_SSANNE_KITCHEN'},
 ['general__rom_082d4dc4']={'FR_SIX_ISLAND_PATTERN_BUSH','FR_VIRIDIAN_FOREST'},
 ['general__rom_082d4df4']={'FR_ROCK_TUNNEL_1F','FR_ROCK_TUNNEL_B1F','FR_SIX_ISLAND_ALTERING_CAVE'},
 ['general__rom_082d4e0c']={'FR_DIGLETTS_CAVE_B1F','FR_DIGLETTS_CAVE_NORTH_ENTRANCE','FR_DIGLETTS_CAVE_SOUTH_ENTRANCE','FR_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY'},
 ['general__rom_082d4e24']={'FR_FOUR_ISLAND_ICEFALL_CAVE_1F','FR_FOUR_ISLAND_ICEFALL_CAVE_B1F','FR_FOUR_ISLAND_ICEFALL_CAVE_BACK','FR_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE','FR_SEAFOAM_ISLANDS_1F','FR_SEAFOAM_ISLANDS_B1F','FR_SEAFOAM_ISLANDS_B2F','FR_SEAFOAM_ISLANDS_B3F','FR_SEAFOAM_ISLANDS_B4F'},
 ['general__rom_082d4e54']={'FR_CERULEAN_CAVE_1F','FR_CERULEAN_CAVE_2F','FR_CERULEAN_CAVE_B1F'},
 ['general__rom_082d4fec']={'FR_MT_EMBER_RUBY_PATH_1F','FR_MT_EMBER_RUBY_PATH_B1F','FR_MT_EMBER_RUBY_PATH_B1F_STAIRS','FR_MT_EMBER_RUBY_PATH_B2F','FR_MT_EMBER_RUBY_PATH_B2F_STAIRS','FR_MT_EMBER_RUBY_PATH_B3F','FR_MT_EMBER_RUBY_PATH_B4F','FR_MT_EMBER_RUBY_PATH_B5F','FR_MT_EMBER_SUMMIT_PATH_1F','FR_MT_EMBER_SUMMIT_PATH_2F','FR_MT_EMBER_SUMMIT_PATH_3F','FR_ONE_ISLAND_KINDLE_ROAD_EMBER_SPA'},
 ['general__rom_082d5004']={'FR_THREE_ISLAND_BERRY_FOREST'},
 ['general__rom_082d501c']={'FR_NAVEL_ROCK_1F','FR_NAVEL_ROCK_B1F','FR_NAVEL_ROCK_BASE','FR_NAVEL_ROCK_BASE_PATH_B10F','FR_NAVEL_ROCK_BASE_PATH_B11F','FR_NAVEL_ROCK_BASE_PATH_B1F','FR_NAVEL_ROCK_BASE_PATH_B2F','FR_NAVEL_ROCK_BASE_PATH_B3F','FR_NAVEL_ROCK_BASE_PATH_B4F','FR_NAVEL_ROCK_BASE_PATH_B5F','FR_NAVEL_ROCK_BASE_PATH_B6F','FR_NAVEL_ROCK_BASE_PATH_B7F','FR_NAVEL_ROCK_BASE_PATH_B8F','FR_NAVEL_ROCK_BASE_PATH_B9F','FR_NAVEL_ROCK_FORK','FR_NAVEL_ROCK_SUMMIT','FR_NAVEL_ROCK_SUMMIT_PATH_2F','FR_NAVEL_ROCK_SUMMIT_PATH_3F','FR_NAVEL_ROCK_SUMMIT_PATH_4F','FR_NAVEL_ROCK_SUMMIT_PATH_5F','FR_SIX_ISLAND_DOTTED_HOLE_1F','FR_SIX_ISLAND_DOTTED_HOLE_B1F','FR_SIX_ISLAND_DOTTED_HOLE_B2F','FR_SIX_ISLAND_DOTTED_HOLE_B3F','FR_SIX_ISLAND_DOTTED_HOLE_B4F','FR_SIX_ISLAND_DOTTED_HOLE_SAPPHIRE_ROOM'},
 ['general__rom_082d5064']={'FR_FIVE_ISLAND','FR_FIVE_ISLAND_MEADOW','FR_FIVE_ISLAND_MEMORIAL_PILLAR','FR_FIVE_ISLAND_RESORT_GORGEOUS','FR_FIVE_ISLAND_WATER_LABYRINTH','FR_FOUR_ISLAND'},
 ['general__rom_082d507c']={'FR_BIRTH_ISLAND_EXTERIOR','FR_SEVEN_ISLAND','FR_SEVEN_ISLAND_SEVAULT_CANYON','FR_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE','FR_SEVEN_ISLAND_TANOBY_RUINS','FR_SEVEN_ISLAND_TRAINER_TOWER','FR_SIX_ISLAND','FR_SIX_ISLAND_GREEN_PATH','FR_SIX_ISLAND_OUTCAST_ISLAND','FR_SIX_ISLAND_RUIN_VALLEY','FR_SIX_ISLAND_WATER_PATH'},
 ['harbor']={'FR_BIRTH_ISLAND_HARBOR','FR_FIVE_ISLAND_HARBOR','FR_FOUR_ISLAND_HARBOR','FR_NAVEL_ROCK_HARBOR','FR_SEVEN_ISLAND_HARBOR','FR_SIX_ISLAND_HARBOR','FR_THREE_ISLAND_HARBOR','FR_TWO_ISLAND_HARBOR','SEVII_ONE_ISLAND_HARBOR'},
 ['house']={'FR_CERULEAN_CITY_HOUSE1','FR_CERULEAN_CITY_HOUSE5','FR_FIVE_ISLAND_HOUSE1','FR_FIVE_ISLAND_HOUSE2','FR_FOUR_ISLAND_HOUSE1','FR_FOUR_ISLAND_HOUSE2','FR_PEWTER_CITY_HOUSE1','FR_PEWTER_CITY_HOUSE2','FR_RIVALS_HOUSE','FR_ROUTE_11_EAST_ENTRANCE_1F','FR_ROUTE_11_EAST_ENTRANCE_2F','FR_ROUTE_12_FISHING_HOUSE','FR_ROUTE_12_NORTH_ENTRANCE_1F','FR_ROUTE_12_NORTH_ENTRANCE_2F','FR_ROUTE_15_WEST_ENTRANCE_1F','FR_ROUTE_15_WEST_ENTRANCE_2F','FR_ROUTE_16_NORTH_ENTRANCE_1F','FR_ROUTE_16_NORTH_ENTRANCE_2F','FR_ROUTE_18_EAST_ENTRANCE_1F','FR_ROUTE_18_EAST_ENTRANCE_2F','FR_ROUTE_19_UNUSED_HOUSE','FR_ROUTE_22_NORTH_ENTRANCE','FR_ROUTE_23_UNUSED_HOUSE','FR_ROUTE_2_EAST_BUILDING','FR_ROUTE_2_HOUSE','FR_ROUTE_2_VIRIDIAN_FOREST_NORTH_ENTRANCE','FR_ROUTE_2_VIRIDIAN_FOREST_SOUTH_ENTRANCE','FR_ROUTE_5_SOUTH_ENTRANCE','FR_ROUTE_6_NORTH_ENTRANCE','FR_ROUTE_6_UNUSED_HOUSE','FR_ROUTE_7_EAST_ENTRANCE','FR_ROUTE_8_WEST_ENTRANCE','FR_SEVEN_ISLAND_HOUSE_ROOM2','FR_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE','FR_SEVEN_ISLAND_UNUSED_HOUSE','FR_SIX_ISLAND_HOUSE','FR_SIX_ISLAND_WATER_PATH_HOUSE1','FR_SIX_ISLAND_WATER_PATH_HOUSE2','FR_THREE_ISLAND_HOUSE2','FR_THREE_ISLAND_HOUSE3','FR_THREE_ISLAND_HOUSE4','FR_THREE_ISLAND_HOUSE5','FR_TWO_ISLAND_CAPE_BRINK_HOUSE','FR_TWO_ISLAND_HOUSE','FR_UNDERGROUND_PATH_EAST_ENTRANCE','FR_UNDERGROUND_PATH_NORTH_ENTRANCE','FR_UNDERGROUND_PATH_SOUTH_ENTRANCE','FR_UNDERGROUND_PATH_WEST_ENTRANCE','FR_VIRIDIAN_CITY_HOUSE','SEVII_ONE_ISLAND_HOUSE1','SEVII_ONE_ISLAND_HOUSE2'},
 ['network']={'FR_CELADON_CITY_POKEMON_CENTER_1F','FR_CELADON_CITY_POKEMON_CENTER_2F','FR_CERULEAN_CITY_POKEMON_CENTER_1F','FR_CERULEAN_CITY_POKEMON_CENTER_2F','FR_CINNABAR_ISLAND_POKEMON_CENTER_1F','FR_CINNABAR_ISLAND_POKEMON_CENTER_2F','FR_FIVE_ISLAND_POKEMON_CENTER_1F','FR_FIVE_ISLAND_POKEMON_CENTER_2F','FR_FOUR_ISLAND_POKEMON_CENTER_1F','FR_FOUR_ISLAND_POKEMON_CENTER_2F','FR_FUCHSIA_CITY_POKEMON_CENTER_1F','FR_FUCHSIA_CITY_POKEMON_CENTER_2F','FR_INDIGO_PLATEAU_POKEMON_CENTER_1F','FR_INDIGO_PLATEAU_POKEMON_CENTER_2F','FR_LAVENDER_TOWN_POKEMON_CENTER_1F','FR_LAVENDER_TOWN_POKEMON_CENTER_2F','FR_PEWTER_CITY_POKEMON_CENTER_1F','FR_PEWTER_CITY_POKEMON_CENTER_2F','FR_ROUTE_10_POKEMON_CENTER_1F','FR_ROUTE_10_POKEMON_CENTER_2F','FR_ROUTE_4_POKEMON_CENTER_1F','FR_ROUTE_4_POKEMON_CENTER_2F','FR_SAFFRON_CITY_POKEMON_CENTER_1F','FR_SAFFRON_CITY_POKEMON_CENTER_2F','FR_SEVEN_ISLAND_POKEMON_CENTER_1F','FR_SEVEN_ISLAND_POKEMON_CENTER_2F','FR_SIX_ISLAND_POKEMON_CENTER_1F','FR_SIX_ISLAND_POKEMON_CENTER_2F','FR_THREE_ISLAND_POKEMON_CENTER_1F','FR_THREE_ISLAND_POKEMON_CENTER_2F','FR_TWO_ISLAND_POKEMON_CENTER_1F','FR_TWO_ISLAND_POKEMON_CENTER_2F','FR_VERMILION_CITY_POKEMON_CENTER_1F','FR_VERMILION_CITY_POKEMON_CENTER_2F','FR_VIRIDIAN_CITY_POKEMON_CENTER_1F','FR_VIRIDIAN_CITY_POKEMON_CENTER_2F','SEVII_ONE_ISLAND_POKECENTER','SEVII_ONE_ISLAND_POKECENTER_2F'},
 ['oak_lab']={'FR_CINNABAR_ISLAND_POKEMON_LAB_ENTRANCE','FR_CINNABAR_ISLAND_POKEMON_LAB_EXPERIMENT_ROOM','FR_CINNABAR_ISLAND_POKEMON_LAB_LOUNGE','FR_CINNABAR_ISLAND_POKEMON_LAB_RESEARCH_ROOM','FR_OAKS_LAB','FR_THREE_ISLAND_HOUSE1'},
 ['pallet_outdoor']={'FR_PALLET_TOWN','FR_ROUTE_1','FR_ROUTE_21_NORTH'},
 ['pewter_gym']={'FR_PEWTER_CITY_GYM','FR_SAFFRON_CITY_DOJO'},
 ['pewter_outdoor']={'FR_PEWTER_CITY','FR_ROUTE_3'},
 ['player_house']={'FR_CELADON_CITY_HOUSE1','FR_CERULEAN_CITY_HOUSE3','FR_CERULEAN_CITY_HOUSE4','FR_FUCHSIA_CITY_HOUSE1','FR_FUCHSIA_CITY_HOUSE3','FR_LAVENDER_TOWN_HOUSE1','FR_LAVENDER_TOWN_HOUSE2','FR_PLAYERS_HOUSE_1F','FR_PLAYERS_HOUSE_2F','FR_ROUTE_16_HOUSE','FR_SAFFRON_CITY_COPYCATS_HOUSE_1F','FR_SAFFRON_CITY_COPYCATS_HOUSE_2F','FR_SAFFRON_CITY_HOUSE','FR_SAFFRON_CITY_MR_PSYCHICS_HOUSE','FR_VERMILION_CITY_HOUSE1','FR_VERMILION_CITY_HOUSE2','FR_VERMILION_CITY_HOUSE3'},
 ['sevii_outdoor']={'FR_MT_EMBER_EXTERIOR','FR_MT_EMBER_SUMMIT','FR_NAVEL_ROCK_EXTERIOR','FR_THREE_ISLAND','FR_THREE_ISLAND_BOND_BRIDGE','FR_THREE_ISLAND_PORT','FR_TWO_ISLAND','FR_TWO_ISLAND_CAPE_BRINK','SEVII_ONE_ISLAND','SEVII_ONE_ISLAND_KINDLE_ROAD','SEVII_ONE_ISLAND_TREASURE_BEACH'},
 ['viridian_outdoor']={'FR_ROUTE_2','FR_ROUTE_22','FR_VIRIDIAN_CITY'},
}
function M.bind(maps)
 aliases={}
 for recipe,ids in pairs(representatives)do
  for _,id in ipairs(ids)do
   local def=maps and maps[id]
   local pair=def and ((def.midLayout and def.midLayout.pair) or def.pair)
   if pair then aliases[pair]=recipe end
  end
 end
end
function M.canonical(pair)return aliases[pair] or pair end
function M.resolve(pair,known)
 pair=M.canonical(pair)
 local spec=known and known[pair]
 if spec then return spec end
 if type(pair)=='string' then
  local primary,secondary=pair:match('^([%w_]+)__(.+)$')
  if primary and secondary then return {primary=primary,secondary=secondary} end
 end
 return {}
end
local caves={rom_082d4bfc=true,rom_082d4df4=true,rom_082d4e0c=true,rom_082d4e24=true,rom_082d501c=true}
function M.cave(spec)return spec and spec.primary=='general' and caves[spec.secondary] or false end
function M.outdoor(def)
 local kind=tonumber(def and def.mapType)
 if kind and kind>0 then return kind==1 or kind==2 or kind==3 or kind==6 end
 return def and (def.environment=='TOWN' or def.environment=='ROUTE') or false
end
function M.supports(def,spec)
 if not (def and def.midLayout) then return false end
 -- Every native building tileset can use the shared camera, primary room
 -- vocabulary and furniture recipes. Unclassified secondary drawings stay
 -- native artwork, not a reason to switch the entire room back to 2D.
 if M.cave(spec) or spec.primary=='building' then return true end
 if spec.primary=='general' then return M.outdoor(def) end
 return spec.primary=='building' and
  (M.canonical(def.midLayout.pair)=='player_house' or M.canonical(def.midLayout.pair)=='house' or M.canonical(def.midLayout.pair)=='oak_lab'
    or M.canonical(def.midLayout.pair)=='network' or M.canonical(def.midLayout.pair)=='building__rom_082d4bcc'
    or M.canonical(def.midLayout.pair)=='pewter_gym')
end
return M
