-- Generated from ModSetting declarations; unsupported adapters remain visible, read-only.
return {
 {key="aa",label="AA",module="AntiAlias"},
 {key="arenaFill",label="ARENA FILL",module="UiBackplates"},
 {key="atmos",label="FOREST FX",module="ForestAtmos"},
 {key="backAnimatedSet",label="BACK ART SET",module="BattleArt"},
 {key="backPlacement",label="BACK PLACEMENT",module="BattleArt"},
 {key="backdropOffset",label="BG Y-OFFSET",module="UiBackplates"},
 {key="battleArt",label="BATTLE ART",module="BattleArt"},
 {key="battleUi",label="BATTLE ART UI",module="UiBackplates"},
 {key="battles",label="3D-BTL",module="OverworldBattle"},
 {key="bossBg",label="BOSS BG",module="UiBackplates"},
 {key="communityCasino",label="CASINO",module="CommunityVisuals"},
 {key="communityCaveDetails",label="CAVE DETAILS",module="CommunityVisuals"},
 {key="communityCaveSound",label="CAVE SOUND",module="CommunityVisuals"},
 {key="communityCaves",label="CAVES",module="CommunityVisuals"},
 {key="communityCityGround",label="CITY GROUND",module="CommunityVisuals"},
 {key="communityCourtyards",label="FENCES & COURTS",module="CommunityVisuals"},
 {key="communityCutTrees",label="CUT TREES",module="CommunityVisuals"},
 {key="communityElevator",label="ROCKET ELEVATOR",module="CommunityVisuals"},
 {key="communityForest",label="VIRIDIAN FOREST",module="CommunityVisuals"},
 {key="communityGrass",label="GRASS",module="CommunityVisuals"},
 {key="communityMasonry",label="WALL & LEDGE COLOR",module="CommunityVisuals"},
 {key="communityPillars",label="LEGENDARY PILLARS",module="CommunityVisuals"},
 {key="communityPrizeRoom",label="PRIZE ROOM",module="CommunityVisuals"},
 {key="communityRoads",label="ROADS & BRIDGES",module="CommunityVisuals"},
 {key="communityRocket",label="ROCKET HIDEOUT",module="CommunityVisuals"},
 {key="communitySigns",label="SIGNS",module="CommunityVisuals"},
 {key="communitySky",label="SKY & BACKGROUND",module="CommunityVisuals"},
 {key="communityTower",label="TOWER VISUALS",module="CommunityVisuals"},
 {key="communityTowerWall",label="TOWER WALL",module="CommunityVisuals"},
 {key="communityTreeDetail",label="TREE DETAIL",module="CommunityVisuals"},
 {key="communityTrees",label="TREES",module="CommunityVisuals"},
 {key="communityTunnels",label="TUNNELS",module="CommunityVisuals"},
 {key="communityWalls",label="WALLS & LEDGES",module="CommunityVisuals"},
 {key="curve",label="V-CURVE",module="WorldCurve"},
 {key="daytime",label="DAYTIME",module="DayNight"},
 {key="duplicateFix",label="DUPLICATE FIX",module="BattleArt"},
 {key="emberLegacyAudio",label="EMBER LEGACY AUDIO",module="PokeballSettings"},
 {key="emberLegacyVolume",label="EMBER LEGACY VOLUME",module="PokeballSettings"},
 {key="fireredBattleStage",label="3D BATTLE STAGE",module="Gen3Battle"},
 {key="fireredCamera",label="2.5D CAMERA",module="Gen3Integration"},
 {key="frontAnimatedSet",label="ANIM FRONT GEN",module="BattleArt"},
 {key="frontFlip",label="FLIP FRONT SPRITE",module="BattleArt"},
 {key="grid",label="V-GRID",module="VoxelGrid"},
 {key="hdTreeTrunks",label="TREE TRUNKS",module="TreePresentation"},
 {key="hudColor",label="HUD COLOR",module="UiBackplates"},
 {key="hudScale",label="HUD SCALE",module="OverworldBattle"},
 {key="interfaceScaling",label="INTERFACE SCALING",module="InterfaceSprites"},
 {key="interfaceSprites",label="INTERFACE SPRITES",module="InterfaceSprites"},
 {key="invertY",label="Y-CONTROL INVERT",module="FirstPerson"},
 {key="legendaryPokeballs",label="EMBER LEGACY",module="PokeballSettings"},
 {key="legendaryVisualsMode",label="LEGENDARY VISUALS",module="LegendaryVisualsPreset"},
 {key="playerAnimatedSet",label="PLAYER ANIM",module="BattleArt"},
 {key="playerArtSet",label="PLAYER ART",module="BattleArt"},
 {key="playerView",label="PLAYER",module="BattleArt"},
 {key="pokeballBeam",label="BEAM STRENGTH",module="PokeballSettings"},
 {key="pokeballCapturePreset",label="CAPTURE FX PRESET",module="PokeballSettings"},
 {key="pokeballCaptureSpeed",label="CAPTURE SPEED",module="PokeballSettings"},
 {key="pokeballFxScale",label="FX SCALE",module="PokeballSettings"},
 {key="pokeballOpenTime",label="BALL OPEN TIME",module="PokeballSettings"},
 {key="pokeballPokemonGlow",label="POKEMON GLOW",module="PokeballSettings"},
 {key="pokeballSize",label="BALL SIZE",module="PokeballSettings"},
 {key="pokeballStreamers",label="STREAMERS",module="PokeballSettings"},
 {key="pokeballSuction",label="SUCTION FX",module="PokeballSettings"},
 {key="pokeballSuctionParticles",label="SUCTION PARTICLES",module="PokeballSettings"},
 {key="ramPrecacheMb",label="RAM PRECACHE MB",module="RamPrecache"},
 {key="renderDistance",label="R.DIST",module="RenderDistance"},
 {key="shadowQuality",label="SHADOWS",module="Shadows"},
 {key="spriteLight",label="SPRITE LIGHT",module="UiBackplates"},
 {key="stadiumCircle",label="STADIUM CIRCLE",module="UiBackplates"},
 {key="standingTrainer",label="STANDING TRAINER",module="OverworldBattle"},
 {key="surfaceArtwork",label="SCENERY TEXTURES",module="TreePresentation"},
 {key="textboxFill",label="TEXTBOX FILL",module="UiBackplates"},
 {key="towerDetails",label="TOWER DETAILS",module="TowerFogSettings"},
 {key="towerFog",label="TOWER FOG",module="TowerFogSettings"},
 {key="towerFogSpeed",label="FOG SPEED",module="TowerFogSettings"},
 {key="towerFogThickness",label="FOG THICKNESS",module="TowerFogSettings"},
 {key="trainerArtSet",label="TRAINER ART",module="BattleArt"},
 {key="treeArtwork",label="TREE ART",module="TreePresentation"},
 {key="water",label="WATER",module="Water"},
 {key="worldFill",label="WORLD FILL",module="WorldUnderlay"},
}
