#!/usr/bin/env python3
"""Build real BW front animation atlases from the existing backs' pinned source.

Artwork is separate from the code license. Raw source GIFs stay in scratch;
release metadata retains each source URL/hash, timings and pixel variance.
"""
import argparse
import concurrent.futures
import hashlib
import io
import json
from pathlib import Path
import time
import urllib.error
import urllib.request

from PIL import Image, ImageSequence

REV = '2ecb4eeacd5a1718621fc30f12772e3f60d830b9'
BASE = f'https://raw.githubusercontent.com/PokeAPI/sprites/{REV}/sprites/pokemon/versions/generation-v/black-white/animated/'


def build(root, cache, dex, variant):
    rel = ('shiny/' if variant == 'shiny' else '') + f'{dex}.gif'
    source = cache / f'{variant}-{dex}.gif'
    if not source.exists():
        for attempt in range(3):
            try:
                with urllib.request.urlopen(BASE + rel, timeout=45) as response:
                    raw = response.read()
                Image.open(io.BytesIO(raw)).verify()
                source.write_bytes(raw)
                break
            except urllib.error.HTTPError as exc:
                if exc.code == 404 or attempt == 2:
                    raise
                time.sleep(attempt + 1)
            except (OSError, ValueError):
                if attempt == 2:
                    raise
                time.sleep(attempt + 1)
    raw = source.read_bytes()
    gif = Image.open(io.BytesIO(raw))
    frames, durations = [], []
    for frame in ImageSequence.Iterator(gif):
        frames.append(frame.convert('RGBA'))
        durations.append(max(20, int(frame.info.get('duration', 100))))
    boxes = [frame.getbbox() for frame in frames]
    if not frames or not all(boxes):
        raise ValueError('empty animation frame')
    box = (min(b[0] for b in boxes), min(b[1] for b in boxes),
           max(b[2] for b in boxes), max(b[3] for b in boxes))
    w, h = box[2] - box[0], box[3] - box[1]
    columns = min(8, len(frames))
    atlas = Image.new('RGBA', (columns * w, ((len(frames) + columns - 1) // columns) * h))
    hashes = set()
    for i, frame in enumerate(frames):
        cell = frame.crop(box)
        hashes.add(hashlib.sha256(cell.tobytes()).hexdigest())
        atlas.paste(cell, ((i % columns) * w, (i // columns) * h))
    target = root / 'assets/bw-front-animated' / variant / f'{dex}.png'
    target.parent.mkdir(parents=True, exist_ok=True)
    atlas.save(target)
    return {'width': w, 'height': h, 'columns': columns, 'frames': len(frames),
            'durations': durations, 'distinctFrames': len(hashes), 'url': BASE + rel,
            'sha256': hashlib.sha256(raw).hexdigest(),
            'atlasSha256': hashlib.sha256(target.read_bytes()).hexdigest()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--cache', type=Path, default=Path('/tmp/johto-hd/bw-front-source'))
    parser.add_argument('--workers', type=int, default=12)
    args = parser.parse_args()
    args.cache.mkdir(parents=True, exist_ok=True)
    rows, missing = {}, {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as pool:
        jobs = {pool.submit(build, args.root, args.cache, dex, variant): f'{variant}/{dex}'
                for dex in range(1, 387) for variant in ('normal', 'shiny')}
        for future in concurrent.futures.as_completed(jobs):
            key = jobs[future]
            try:
                rows[key] = future.result()
            except Exception as exc:
                missing[key] = str(exc)
            if (len(rows) + len(missing)) % 100 == 0:
                print(f'Imported {len(rows)}; missing {len(missing)}', flush=True)
    out = args.root / 'assets/bw-front-animated'
    out.mkdir(parents=True, exist_ok=True)
    (out / 'sources.json').write_text(json.dumps({'revision': REV, 'sprites': rows, 'missing': missing}, indent=2, sort_keys=True) + '\n')
    lines = ['-- Generated by tools/import_bundled_bw_fronts.py; timing is milliseconds.', 'return {']
    for key, row in sorted(rows.items()):
        durations = ','.join(map(str, row['durations']))
        lines.append(f' ["{key}"]={{width={row["width"]},height={row["height"]},columns={row["columns"]},frames={row["frames"]},durations={{{durations}}}}},')
    (args.root / 'data/bundled_bw_fronts.lua').write_text('\n'.join(lines) + '\n}\n')
    static = [key for key, row in rows.items() if row['distinctFrames'] < 2]
    print(json.dumps({'imported': len(rows), 'animated': len(rows) - len(static),
                      'static': sorted(static), 'missing': missing}, sort_keys=True), flush=True)
    if missing:
        raise SystemExit(1)


if __name__ == '__main__':
    main()
